String SPLASH_SCREEN='SPLASH_SCREEN';
String HOME_SCREEN='HOME_SCREEN';
String MyReview_Screen='MyReview_Screen';
String ITEM_DETAILS_SCREEN='ITEM_DETAILS_SCREEN';
String GRID_ITEM_DETAILS_SCREEN='GRID_ITEM_DETAILS_SCREEN';